# --------------------------------------------------------------------------------
#
#  This is the authoritative file that defines how the database will
#  load the category and field structure
#
# --------------------------------------------------------------------------------
#
#   This file defines a simple DSL to represent the form structure to be used
#     to specify project requests and automatically generate forms
#
#   All attributes belong to the following categories:
#
#
#  == Required Attributes ==
#
#   - attr_name (Symbol):
#       (ex - :wall_1, :wall_2)
#
#
#  == Optional Attributes ==
#
#   - field_data: (Array/Hash)
#       (ex - [:walls, :ceiling, :trim, :doors, :windows])
#
#   - label: (String)
#       (ex - "Wall 1 (Square Feet)")
#
#   - position: (enum: [:left, :right])
#       (ex - :left)
#
#   - size: (enum: [:tiny, :small, :normal, :large])
#       (ex - :left)
#
#   - default: (String/Boolean)
#       (ex - "Wood", true)
#
#   - required: (True/False)
#       True if this field is required
#
#   - toggleable: True/False
#       True if this field can be enabled/disabled by a check box.
#
#     Collections (Dropdown):
#       - List of strings for the user to select such as paint type/etc
#
#
#
#  This data has been populated from pricing.xlsx and project_request_variables.xslx
#
#   ** All Nested fields are delimited by two spaces of indentation **
#
#  - AE on 6/21/13
#
#
#
# END COMMENTS ---------------------------------------------------------------

#META:
#  EDIT_BY:
#    - Your name here
#    - Anthony
#  EDIT_NOTES:
#    - Your note here
#    - Removed some extra fields. All calculator fields have been moved to a separate YML file.

painting:   # (TOP-LEVEL PROJECT CATEGORIES 0 SPACES INDENTED) (E.g. Painting, Plumbing, General Contractor)

  # Project category params will go here (Two spaces of indentation) -----------------------------
  interior_painting:
    # Project category fields will go here (Four spaces of indentation) -----------------------------
    wall_1:
      field_type: text_field
      label: "Square footage of Wall 1"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_2:
      field_type: text_field
      label: "Square footage of Wall 2"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_3:
      field_type: text_field
      label: "Square footage of Wall 3"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_4:
      field_type: text_field
      label: "Square footage of Wall 4"
      data_type: decimal
      toggleable: "Check if needs paint"
    ceiling:
      field_type: text_field
      label: "Square footage of ceiling"
      data_type: decimal
      toggleable: "Check if needs paint"

    surfaces:
      field_type: select
      field_data:
        - Walls
        - Ceiling
        - Trim
        - Doors
        - Windows

    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

    condition:
      label: "Current surface condition"
      field_type: select
      field_data:
        - Excellent - No repair necessary
        - Fair - Minor repair necessary
        - Poor - Major repair necessary

  exterior_painting:  # EXTERIOR PAINTING -------------------------------------------------------------------------------------
    # Project category fields will go here (Four spaces of indentation) -----------------------------
    wall_1:
      field_type: text_field
      label: "Square footage of Wall 1"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_2:
      field_type: text_field
      label: "Square footage of Wall 2"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_3:
      field_type: text_field
      label: "Square footage of Wall 3"
      data_type: decimal
      toggleable: "Check if needs paint"
    wall_4:
      field_type: text_field
      label: "Square footage of Wall 4"
      data_type: decimal
      toggleable: "Check if needs paint"
    ceiling:
      field_type: text_field
      label: "Square footage of ceiling"
      data_type: decimal
      toggleable: "Check if needs paint"

    surfaces:
      field_type: select
      field_data:
        - Siding
        - Trim
        - Doors
        - Windows
        - Shutters
        - Porch

    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

    condition:
      label: "Current surface condition"
      field_type: select
      field_data:
        - Excellent - No repair necessary
        - Fair - Minor repair necessary
        - Poor - Major repair necessary

  concrete:         # (PROJECT SUB CATEGORIES 2 SPACES INDENTED) (Starts with a #) ---------------------------
    location:         # Project sub-type attributes are 4 spaces indented
      field_type: select
      field_data:
        - interior        # Types that go in a drop-down start with a - (an collection of strings)
        - exterior
    desired_finish:
      field_type: select
      field_data:
        - Stain / Coloring
        - Paint / Epoxy
        - Clear Sealant
    dimensions:
      field_type: text_field
      Number Square Feet: :decimal  # 'SINGLE' attribute types have an associated type (:integer in this case)

  cleaning:
    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

  flooring:
    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

  lawn_care:
    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

  other_painting:
    finish_type:
      label: "Finish type"
      field_type: select
      field_data:
        - Unfinished
        - Painted
        - Wallpapered

cleaning:
  interior_cleaning:
      # Project category fields will go here (Four spaces of indentation) -----------------------------
      wall_1:
        field_type: text_field
        label: "Square footage of Wall 1"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_2:
        field_type: text_field
        label: "Square footage of Wall 2"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_3:
        field_type: text_field
        label: "Square footage of Wall 3"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_4:
        field_type: text_field
        label: "Square footage of Wall 4"
        data_type: decimal
        toggleable: "Check if needs paint"
      ceiling:
        field_type: text_field
        label: "Square footage of ceiling"
        data_type: decimal
        toggleable: "Check if needs paint"

      surfaces:
        field_type: select
        field_data:
          - Walls
          - Ceiling
          - Trim
          - Doors
          - Windows

      finish_type:
        label: "Finish type"
        field_type: select
        field_data:
          - Unfinished
          - Painted
          - Wallpapered

flooring:
  interior_cleaning:
      # Project category fields will go here (Four spaces of indentation) -----------------------------
      wall_1:
        field_type: text_field
        label: "Square footage of Wall 1"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_2:
        field_type: text_field
        label: "Square footage of Wall 2"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_3:
        field_type: text_field
        label: "Square footage of Wall 3"
        data_type: decimal
        toggleable: "Check if needs paint"
      wall_4:
        field_type: text_field
        label: "Square footage of Wall 4"
        data_type: decimal
        toggleable: "Check if needs paint"
      ceiling:
        field_type: text_field
        label: "Square footage of ceiling"
        data_type: decimal
        toggleable: "Check if needs paint"

      surfaces:
        field_type: select
        field_data:
          - Walls
          - Ceiling
          - Trim
          - Doors
          - Windows

      finish_type:
        label: "Finish type"
        field_type: select
        field_data:
          - Unfinished
          - Painted
          - Wallpapered


#    Flat:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Panel:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    French:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Louvered:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Bifold:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Garage:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Single Pane:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Multi Pane:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Bay:
#      enabled: boolean
#      quantity: integer, if: :enabled
#    Shutters:
#      enabled: boolean
#      quantity: integer, if: : enabled
#    Decking:
#      feet: decimal
#    Railing:
#      feet: decimal
#    Posts:
#      quantity: integer
#    Steps:
#      quantity: integer
#    Siding Type:
#      - Vinyl
#      - Fiber Cement
#      - Composite Shake
#      - Cedar Shake
#      - T 1-11
#      - Stucco
#      - Aluminum
#      - Brick
#    Condition:
#      - Excellent - No repair necessary
#      - Fair - Minor repair necessary
#      - Poor - Major repair necessary


#  concrete:  # CONCRETE PAINTING -------------------------------------------------------------------------------------
#    Desired Finish:
#      - Paint
#      - Epoxy
#      - Textured Coating
#      - Stain Only
#      - Sealant Only
#      - Stain & Sealant
#    Square Footage:
#      feet: decimal
#
#    concrete_calculator:  # CONCRETE PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Concrete Coating:
#        Hours per square foot of Paint: 0.015
#        Hours per square foot of Epoxy: 0.025
#        Hours per square foot of Textured Coating: 0.02
#        Hours per square foot of Stain Only: 0.02
#        Hours per square foot of Sealant Only: 0.02
#        Hours per square foot of Stain & Sealant: 0.03
#
#
#  fence:  # FENCE PAINTING -------------------------------------------------------------------------------------
#    Fence Type:
#      - Wood Board
#      - Wrought Iron
#      - Chain Link
#      - Lattice
#      - Concrete
#      - Vinyl
#      - Other
#    Number of Sides:
#      - 1
#      - 2
#    Length:
#      feet: decimal
#    Height:
#      feet: decimal
#    Current Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Condition:
#      - Excellent - No repair necessary
#      - Fair - Minor repair necessary
#      - Poor - Major repair necessary
#    Desired Finish:
#      - Painted
#      - Stained
#
#    fence_calculator:  # FENCE PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Fence Paint:
#        Hours per square foot of Wood Board: 0.015
#        Hours per square foot of Wrought Iron: 0.03
#        Hours per square foot of Chain Link: 0.02
#        Hours per square foot of Vinyl: 0.025
#        Hours per square foot of Lattice: 0.03
#        Hours per square foot of Concrete: 0.02
#        Multiplier for 2 sides: 2
#        Multiplier for fair condition: 1.5
#        Multiplier for poor condition: 2
#
#  flooring:  # FLOORING PAINTING -------------------------------------------------------------------------------------
#    Current Finish:
#      - Unfinished
#      - Stain & Urethane
#      - Paint
#      - Wax
#    Condition:
#      - Excellent - No repair necessary
#      - Fair - Minor repair necessary
#      - Poor - Major repair necessary
#    Desired Finish:
#      - Stain & Urethane
#      - Paint
#      - Wax
#    Square Footage:
#      feet: decimal
#
#    flooring_calculator:  # FLOORING PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Fence Paint:
#        Hours per square foot of Sanding: 0.02
#        Hours per square foot of Stain & Urethane: 0.01
#        Hours per square foot of Paint: 0.01
#        Hours per square foot of Wax: 0.015
#
#  window:  #  WINDOW PAINTING -------------------------------------------------------------------------------------
#    Current Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Desired Finish:
#      - Painted
#      - Stained
#    Single Pane:
#      quantity: integer
#    Multi Pane:
#      quantity: integer
#    Bay:
#      quantity: integer
#    Shutters:
#      quantity: integer
#
#    window_calculator:  # WINDOW PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Window Paint:
#        Hours per single pane: 1
#        Hours per multiple pane: 2
#        Hours per bay: 3
#        Multiplier for sanding: 1.5
#
#
#  door:  #  DOOR PAINTING -------------------------------------------------------------------------------------
#    Current Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Desired Finish:
#      - Painted
#      - Stain
#    Flat:
#      quantity: integer
#    Panel:
#      quantity: integer
#    French:
#      quantity: integer
#    Louvered:
#      quantity: integer
#    Bifold:
#      quantity: integer
#    Garage:
#      quantity: integer
#
#
#    door_calculator:  # DOOR PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Door Paint:
#        Hours per flat: 1
#        Hours per bifold: 1.5
#        Hours per paneled: 1.5
#        Hours per louvered: 2.5
#        Hours per french: 2.5
#        Hours per Garage: 2.5
#
#   deck:  # DECK PAINTING -------------------------------------------------------------------------------------
#    Decking:
#      feet: decimal
#      Check if needs paint: boolean
#    Stairs:
#      quantity: integer
#      Check if needs paint: boolean
#    Railings:
#      Check if needs paint: boolean
#    Lattice:
#      Check if needs paint: boolean
#    Pergola:
#      Check if needs paint: boolean
#    Current Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Condition:
#      - Excellent - No repair necessary
#      - Fair - Minor repair necessary
#      - Poor - Major repair necessary
#     Desired Finish:
#      - Painted
#      - Stained
#
#    deck_calculator:  # DECK PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Decking:
#        Hours per square foot: 0.015
#        Multiplier for 'fair' condition: 1.5
#        Multiplier for 'poor' condition: 2.0
#        Multiplier for sanding: 1.25
#
#      Stairs:
#        Hours per stair: 0.2
#        Multiplier for 'fair' condition: 1.5
#        Multiplier for 'poor' condition: 2.0
#        Multiplier for sanding: 1.25
#
#      Railings:
#        Hours per linear foot of Railing: 0.03
#        Multiplier for 'fair' condition: 1.5
#        Multiplier for 'poor' condition: 2.0
#        Multiplier for sanding: 1.25
#
#      Lattice:
#        Hours per linear foot of Lattice: 0.03
#        Multiplier for 'fair' condition: 1.5
#        Multiplier for 'poor' condition: 2.0
#        Multiplier for sanding: 1.25
#
#      Pergola:
#        Hours per square foot of Pergola: 0.03
#        Multiplier for 'fair' condition: 1.5
#        Multiplier for 'poor' condition: 2.0
#        Multiplier for sanding: 1.25
#
#  powerwashing:  # POWERWASHING -------------------------------------------------------------------------------------
#    Home Exterior:
#      enabled: boolean
#    Patio / Driveway:
#      enabled: boolean
#    Roof:
#      enabled: boolean
#    Deck:
#      enabled: boolean
#    Fence:
#      enabled: boolean
#    Number of Stories
#      quantity: integer
#    Wall 1:
#      feet: decimal
#      Check if needs paint: boolean
#    Wall 2:
#      feet: decimal
#      Check if needs paint: boolean
#    Wall 3:
#      feet: decimal
#      Check if needs paint: boolean
#    Wall 4:
#      feet: decimal
#      Check if needs paint: boolean
#    Number of Windows Washed:
#      quantity: integer
#    Roof Type:
#      - Asphalt Shingle
#      - Metal
#      - Clay / Concrete Tile
#      - Wood Shingle
#      - Slate
#    Roof Size:
#      feet: decimal
#    Patio Size:
#      feet: decimal
#    Decking:
#      enabled: boolean
#    Stairs:
#      enabled: boolean
#    Railings:
#      enabled: boolean
#    Lattice:
#      enabled: boolean
#    Pergola:
#      enabled: boolean
#    Deck Size:
#      feet: decimal
#    Number of Stairs:
#      quantity: integer
#    Number of Fence Sides
#      quantity: integer
#    Fence Length:
#      feet: decimal
#    Fence Height:
#      feet: decimal
#
#  powerwashing_calculator:  # POWERWASHING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#    Exterior:
#      Hours per square foot of siding: 0.0025
#      Multiplier above 1 story: 0.15
#
#    Windows:
#      Hours per Window: 0.25
#      Multiplier above 1 story: 0.15
#
#    Roof:
#      Hours per square foot of decking: 0.0035
#      Multiplier above 1 story: 1.15
#
#    Patio:
#      Hours per square foot of patio: 0.0035
#
#    Deck:
#      Hours per square foot of decking: 0.0035
#      Hours per stair: 0.05
#      Hours per linear foot of railing: 0.05
#      Hours per linear foot of lattice: 0.05
#      Hours per square foot of pergola: 0.01
#
#    Fence:
#      Hours per square foot of fence: 0.0035
#
#  stairs:  # STAIR PAINTING -------------------------------------------------------------------------------------
#    Treads:
#      enabled: boolean
#    Risers:
#      enabled: boolean
#    Railings:
#      enabled: boolean
#    Balusters:
#      enabled: boolean
#    Surface Condition:
#      - Excellent - No repair necessary
#      - Fair - Minor repair necessary
#      - Poor - Major repair necessary
#    Number of Stairs:
#      quantity: integer
#    Current Tread Finish:
#      - Carpet
#      - Finished Wood and Carpet
#      - Finished Wood
#      - Unfinished Wood
#      - Painted Wood
#    Desired Tread Finish
#      - Finished Wood (Stain)
#      - Finished Wood (Stain) and Carpet
#      - Painted Wood
#    Current Riser Finish:
#      - Carpet
#      - Finished Wood and Carpet
#      - Finished Wood
#      - Unfinished Wood
#      - Painted Wood
#    Desired Riser Finish
#      - Finished Wood (Stain)
#      - Finished Wood (Stain) and Carpet
#      - Painted Wood
#    Current Railing Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Desired Railing Finish
#      - Unfinished
#      - Painted
#      - Stained
#    Current Baluster Finish:
#      - Unfinished
#      - Painted
#      - Stained
#    Desired Baluster Finish
#      - Unfinished
#      - Painted
#      - Stained
#
#    stairs_calculator:  # STAIRS PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
#      Tread:
#        Hours per Stair: 0.15
#        Multiplier for carpet or re-staining: 2.5
#        Multiplier for fair condition: 1.5
#        Multiplier for poor condition: 2.0
#
#      Riser:
#        Hours per Stair: 0.1
#        Multiplier for carpet or re-staining: 2.5
#        Multiplier for fair condition: 1.5
#        Multiplier for poor condition: 2.0
#
#      Railing:
#        Hours per Stair: 0.1
#        Multiplier for re-staining: 2.5
#        Multiplier for fair condition: 1.5
#        Multiplier for poor condition: 2.0
#
#      Baluster:
#        Hours per Stair: 0.5
#        Multiplier for re-staining: 2.5
#        Multiplier for fair condition: 1.5
#        Multiplier for poor condition: 2.0
