contractor_specialties:
  Additions &amp; Remodeling
  Air Conditioning
  Architects &amp; Engineers
  Audio/Visual &amp; Computers
  Brick &amp; Stone
  Cleaning &amp; Maid Services
  Concrete
  Decks
  Designers &amp; Decorators
  Drywall&amp; Plaster
  Electrical
  Fences
  Flooring &amp; Carpet
  Furniture Repair &amp; Refinish
  Garage &amp; Garage Doors
  Handyman Services
  Heating &amp; Furnace Systems
  Landscaping
  Lawn &amp; Garden Care
  Mold &amp; Asbestos Services
  New Home Builders
  Painting
  Paving
  Plumbing
  Roofing
  Sheds &amp; Enclosures
  Siding
  Swimming Pools
  Tile
  Tree Service
  Waste Material Removal
  Windows