contractor_specialties:
  - Additions & Remodeling
  - Air Conditioning
  - Architects & Engineers
  - Audio/Visual & Computers
  - Brick & Stone
  - Cleaning & Maid Services
  - Concrete
  - Decks
  - Designers & Decorators
  - Drywall & Plaster
  - Electrical
  - Fences
  - Flooring & Carpet
  - Furniture Repair &amp; Refinish
  - Garage & Garage Doors
  - Handyman Services
  - Heating & Furnace Systems
  - Landscaping
  - Lawn & Garden Care
  - Mold & Asbestos Services
  - New Home Builders
  - Paving
  - Plumbing
  - Roofing
  - Sheds & Enclosures
  - Siding
  - Swimming Pools
  - Tile
  - Tree Service
  - Waste Material Removal
  - Windows