# COMMENTS AND EXAMPLES (COMMENTS starts with a #) ---------------------------
#
#   This file defines a simple DSL to represent the form structure to be used
#     to specify project requests and automatically generate forms
#
#   All attributes belong to the following categories:
#
#     Text-Field Inputs:
#       - decimal: Measurements such as height/width
#       - integer: Discrete Quantities
#       - boolean: For checkboxes
#       - string: Explainations (Limited to 255 characters)
#       - text: Descriptions
#
#     Collections (Dropdown):
#       - List of strings for the user to select such as paint type/etc
#
#
#  This data has been populated from pricing.xlsx and project_request_variables.xslx
#
#   ** All Nested fields are delimited by two spaces of indentation **
#
#
#  - AE on 6/21/13
#
# END COMMENTS ---------------------------------------------------------------

painting:   # (TOP-LEVEL PROJECT CATEGORIES 0 SPACES INDENTED) (E.g. Painting, Plumbing, General Contractor)
  concrete:         # (PROJECT SUB CATEGORIES 2 SPACES INDENTED) (Starts with a #) ---------------------------
    location:         # Project sub-type attributes are 4 spaces indented
      - interior        # Types that go in a drop-down start with a - (an collection of strings)
      - exterior
    desired_finish:
      - Stain / Coloring
      - Paint / Epoxy
      - Clear Sealant
    dimensions:
      Number Square Feet: :decimal  # 'SINGLE' attribute types have an associated type (:integer in this case)

    concrete_calculator:    # EACH PROJECT TYPE WILL HAVE AN ASSOCIATED 'CALCULATOR' defining attributes and their defaults
      concrete coating:
        pricing:
          Paint: 0.015
          Epoxy: 0.025
          Textured Coating: 0.02
          Stain Only: 0.02
          Sealant Only: 0.02
          Stain & Sealant: 0.03


  interior:  # INTERIOR PAINTING -------------------------------------------------------------------------------------
    Wall 1:
      feet: decimal
      Check if needs paint: boolean
    Wall 2:
      feet: decimal
      Check if needs paint: boolean
    Wall 3:
      feet: decimal
      Check if needs paint: boolean
    Wall 4:
      feet: decimal
      Check if needs paint: boolean
    Ceiling Height:
      feet: decimal
    Surfaces:
      - Walls
      - Ceiling
      - Trim
      - Doors
      - Windows
    Flat:
      enabled: boolean
      quantity: integer, if: :enabled
    Panel:
      enabled: boolean
      quantity: integer, if: :enabled
    French:
      enabled: boolean
      quantity: integer, if: :enabled
    Louvered:
      enabled: boolean
      quantity: integer, if: :enabled
    Bifold:
      enabled: boolean
      quantity: integer, if: :enabled
    Single Pane:
      enabled: boolean
      quantity: integer, if: :enabled
    Multi Pane:
      enabled: boolean
      quantity: integer, if: :enabled
    Bay:
      enabled: boolean
      quantity: integer, if: :enabled
    Current Wall Finish:
      - Unfinished
      - Painted
      - Wallpapered
    Condition:
      - Excellent - No repair necessary
      - Fair - Minor repair necessary
      - Poor - Major repair necessary
    Desired Wall Finish:
      - Painted
      - Wallpapered

    interior_calculator:  # INTERIOR PAINTING PROJECT CATEGORY SUBTYPE ------------------------------------------------
      Wall Paint:
        Hours per square foot: 0.015
        Multiplier for height over 8' (per add'l ft): 0.05
        Multiplier for 'fair' condition: 1.5
        Multiplier for 'poor' condition: 2

      Wall Prime:
      	Hours per square foot: 0.01
          Mulitplier for height over 8' (per add'l ft): 0.05

      Wallpaper Hanging/Removal:
        Hours per square foot: 0.025
        Mulitplier for height over 8' (per add'l ft):	0.05

      Ceiling Paint:
        Hours per square foot: 0.02
        Mulitplier for height over 8' (per add'l ft): 0.05
        Multiplier for 'fair' condition: 1.5
        Multiplier for 'poor' condition: 2

      Trim:
        Hours per linear foot (all trim): 0.025
        Mulitplier for height over 8' (per add'l ft - crown only): 0.05

      Doors:
        Hours per flat: 1
        Hours per bifold: 1.5
        Hours per paneled: 1.5
        Hours per louvered: 2.5
        Hours per French: 2.5

      Windows:
        Hours per single pane: 1
        Hours per muliple pane: 2
        Hours per bay: 3


  ## TO BE CONTINUED HERE ---------------------------------------------------------------------------------------------
  ## TO BE CONTINUED HERE ---------------------------------------------------------------------------------------------
  ## TO BE CONTINUED HERE ---------------------------------------------------------------------------------------------