require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailinglistsController do

  # This should return the minimal set of attributes required to create a valid
  # Mailinglist. As you add validations to Mailinglist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "email" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailinglistsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mailinglists as @mailinglists" do
      mailinglist = Mailinglist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mailinglists).should eq([mailinglist])
    end
  end

  describe "GET show" do
    it "assigns the requested mailinglist as @mailinglist" do
      mailinglist = Mailinglist.create! valid_attributes
      get :show, {:id => mailinglist.to_param}, valid_session
      assigns(:mailinglist).should eq(mailinglist)
    end
  end

  describe "GET new" do
    it "assigns a new mailinglist as @mailinglist" do
      get :new, {}, valid_session
      assigns(:mailinglist).should be_a_new(Mailinglist)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailinglist as @mailinglist" do
      mailinglist = Mailinglist.create! valid_attributes
      get :edit, {:id => mailinglist.to_param}, valid_session
      assigns(:mailinglist).should eq(mailinglist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mailinglist" do
        expect {
          post :create, {:mailinglist => valid_attributes}, valid_session
        }.to change(Mailinglist, :count).by(1)
      end

      it "assigns a newly created mailinglist as @mailinglist" do
        post :create, {:mailinglist => valid_attributes}, valid_session
        assigns(:mailinglist).should be_a(Mailinglist)
        assigns(:mailinglist).should be_persisted
      end

      it "redirects to the created mailinglist" do
        post :create, {:mailinglist => valid_attributes}, valid_session
        response.should redirect_to(Mailinglist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailinglist as @mailinglist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailinglist.any_instance.stub(:save).and_return(false)
        post :create, {:mailinglist => { "email" => "invalid value" }}, valid_session
        assigns(:mailinglist).should be_a_new(Mailinglist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailinglist.any_instance.stub(:save).and_return(false)
        post :create, {:mailinglist => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailinglist" do
        mailinglist = Mailinglist.create! valid_attributes
        # Assuming there are no other mailinglists in the database, this
        # specifies that the Mailinglist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mailinglist.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => mailinglist.to_param, :mailinglist => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested mailinglist as @mailinglist" do
        mailinglist = Mailinglist.create! valid_attributes
        put :update, {:id => mailinglist.to_param, :mailinglist => valid_attributes}, valid_session
        assigns(:mailinglist).should eq(mailinglist)
      end

      it "redirects to the mailinglist" do
        mailinglist = Mailinglist.create! valid_attributes
        put :update, {:id => mailinglist.to_param, :mailinglist => valid_attributes}, valid_session
        response.should redirect_to(mailinglist)
      end
    end

    describe "with invalid params" do
      it "assigns the mailinglist as @mailinglist" do
        mailinglist = Mailinglist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailinglist.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailinglist.to_param, :mailinglist => { "email" => "invalid value" }}, valid_session
        assigns(:mailinglist).should eq(mailinglist)
      end

      it "re-renders the 'edit' template" do
        mailinglist = Mailinglist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailinglist.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailinglist.to_param, :mailinglist => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailinglist" do
      mailinglist = Mailinglist.create! valid_attributes
      expect {
        delete :destroy, {:id => mailinglist.to_param}, valid_session
      }.to change(Mailinglist, :count).by(-1)
    end

    it "redirects to the mailinglists list" do
      mailinglist = Mailinglist.create! valid_attributes
      delete :destroy, {:id => mailinglist.to_param}, valid_session
      response.should redirect_to(mailinglists_url)
    end
  end

end
